"""добавлено поле режиссера в таблицу фильмов

Revision ID: 0be1d96aea83
Revises: b5ddd5be33ad
Create Date: 2025-05-08 22:17:11.923884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be1d96aea83'
down_revision: Union[str, None] = 'b5ddd5be33ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('director', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'director')
    # ### end Alembic commands ###
