"""Добавлен заголовок для офиса

Revision ID: 396e19b079d5
Revises: 0be1d96aea83
Create Date: 2025-05-09 21:41:25.743627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396e19b079d5'
down_revision: Union[str, None] = '0be1d96aea83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'title')
    # ### end Alembic commands ###
