"""добавлен маркер активности для зала

Revision ID: 48519afc2d0e
Revises: 2edd53922f6d
Create Date: 2025-03-03 21:44:03.545827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48519afc2d0e'
down_revision: Union[str, None] = '2edd53922f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('halls', 'active')
    # ### end Alembic commands ###
