"""добавлено поле даты регистрации пользователя

Revision ID: 666fa7376771
Revises: a25f8de4b592
Create Date: 2025-06-01 21:54:09.560237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666fa7376771'
down_revision: Union[str, None] = 'a25f8de4b592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_data')
    # ### end Alembic commands ###
