"""добавлено поле рейтинга фильмам

Revision ID: 7e8a7835d15f
Revises: 48519afc2d0e
Create Date: 2025-03-04 21:29:13.184854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8a7835d15f'
down_revision: Union[str, None] = '48519afc2d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('rating', sa.DECIMAL(precision=4, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'rating')
    # ### end Alembic commands ###
