"""empty message

Revision ID: 8db724e4f93f
Revises: fec44cb2ff1c
Create Date: 2025-03-14 20:01:39.921276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db724e4f93f'
down_revision: Union[str, None] = 'fec44cb2ff1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announces', sa.Column('cover_url', sa.Text(), nullable=False))
    op.add_column('halls', sa.Column('office', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_halls_offices_id_office', 'halls', 'offices', ['office'], ['id'])
    op.add_column('orders', sa.Column('office', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_orders_offices_id_office', 'orders', 'offices', ['office'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_offices_id_office', 'orders', type_='foreignkey')
    op.drop_column('orders', 'office')
    op.drop_constraint('fk_halls_offices_id_office', 'halls', type_='foreignkey')
    op.drop_column('halls', 'office')
    op.drop_column('announces', 'cover_url')
    # ### end Alembic commands ###
