"""добавлена таблица платежа

Revision ID: 9c2b526c6ec2
Revises: a19257bc6e95
Create Date: 2025-06-03 17:59:31.130050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c2b526c6ec2'
down_revision: Union[str, None] = 'a19257bc6e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_payments_orders_id_order', 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_orders_id_order', 'payments', 'orders', ['order'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payments_orders_id_order', 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_orders_id_order', 'payments', 'orders', ['order'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('payments', 'order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
