"""фикс поля даты регистрации пользователя

Revision ID: a19257bc6e95
Revises: 666fa7376771
Create Date: 2025-06-01 22:03:31.898545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a19257bc6e95'
down_revision: Union[str, None] = '666fa7376771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'registration_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_data', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###
