"""добавлены актеры с привязкой к фильмам

Revision ID: a86f0f08e8b1
Revises: 8db724e4f93f
Create Date: 2025-03-14 22:47:00.253365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86f0f08e8b1'
down_revision: Union[str, None] = '8db724e4f93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
