"""заказ теперь может быть и не привязан к заказу + добавлен аватар пользователю

Revision ID: b5ddd5be33ad
Revises: e7c7d82dda9e
Create Date: 2025-05-03 18:31:23.949048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ddd5be33ad'
down_revision: Union[str, None] = 'e7c7d82dda9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
