"""бонус логи теперь привязаны к заказам + добавлено поле даты создания

Revision ID: cb1df44c65b7
Revises: 396e19b079d5
Create Date: 2025-05-13 01:02:19.359411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb1df44c65b7'
down_revision: Union[str, None] = '396e19b079d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_logs', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('bonus_logs', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_constraint('fk_bonus_logs_films_id_film', 'bonus_logs', type_='foreignkey')
    op.create_foreign_key('fk_bonus_logs_orders_id_order', 'bonus_logs', 'orders', ['order'], ['id'])
    op.drop_column('bonus_logs', 'film')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_logs', sa.Column('film', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_bonus_logs_orders_id_order', 'bonus_logs', type_='foreignkey')
    op.create_foreign_key('fk_bonus_logs_films_id_film', 'bonus_logs', 'films', ['film'], ['id'])
    op.drop_column('bonus_logs', 'date_created')
    op.drop_column('bonus_logs', 'order')
    # ### end Alembic commands ###
