"""теперь у одного заказа может быть несколько мест

Revision ID: cb7acb741cec
Revises: cb1df44c65b7
Create Date: 2025-05-28 17:32:39.878298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb7acb741cec'
down_revision: Union[str, None] = 'cb1df44c65b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_seats_id_seat', 'orders', type_='foreignkey')
    op.drop_column('orders', 'seat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seat', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_orders_seats_id_seat', 'orders', 'seats', ['seat'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
