"""добавлено поле email юзеру + статус заказа и цена заказа

Revision ID: e7c7d82dda9e
Revises: a86f0f08e8b1
Create Date: 2025-05-03 01:28:19.017506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c7d82dda9e'
down_revision: Union[str, None] = 'a86f0f08e8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('NOT_PAID', 'PAID', 'COMPLETE', 'POSTPONED', 'CANCELED', 'REFUND', name='orderstatuses'), nullable=False))
    op.add_column('orders', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
