"""добавлены офисы, регионы и рекламы фильмов

Revision ID: fec44cb2ff1c
Revises: 7e8a7835d15f
Create Date: 2025-03-14 18:46:25.202718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec44cb2ff1c'
down_revision: Union[str, None] = '7e8a7835d15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
